package org.example;

import io.javalin.http.Context;
import io.javalin.http.Handler;

public class HomeHandler implements Handler {
    @Override
    public void handle(Context ctx){
        ctx.result("Hello Sir/Mam, this is our url shortener. " +
                "If you want to generate a short url of you long url, " +
                "you can you use our service or if you have already a short url generated by us, just use it!");
    }
}
