package org.example;

import java.security.SecureRandom;
import java.util.Map;
import java.util.Optional;

import io.javalin.Javalin;

public class Main {
     public static void main(String[] args) throws Exception {
         UrlRepository repo = new UrlRepository(Database.getDataSource());

         var app = Javalin.create(config -> {
             config.routes.get("/", ctx -> ctx.result("Hello Sir, this is our url shortener. If you want to generate a short" +
                     "url of you long url, you can you use our service or if you have already a short url generated by us, just use it!"));
             config.routes.get("/{url}", ctx ->{
                String shortUrl = ctx.pathParam("url");
                Optional<String> longUrl = repo.findByShortCode(shortUrl);
                if(longUrl.isPresent()) ctx.redirect(longUrl.get());
                else ctx.status(404);
             });
             config.routes.post("/api/shorten", ctx -> {
                 ShortenReq req = ctx.bodyAsClass(ShortenReq.class);
                 String longUrl = req.url;
                 UrlService service = new UrlService();
                 String code = service.createShortUrl(longUrl, repo);
                 String shortUrl = "http://localhost:7070/" + code;
                 ctx.json(Map.of("shortUrl", shortUrl));
             });
         }).start(7070);
    }
}